version: '3.9'


services:
  backend:
    container_name: django
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./env_variables.env
    volumes:
      - ./backend:/app
    command: python3 manage.py runserver 0.0.0.0:8000


  redis:
    container_name: blog-redis
    image: redis
    ports:
      - '6369:6379'
    restart: always
    command: 'redis-server --save --loglevel warning'


  smtp4dev:
    container_name: smtp_blog
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

  beat:
    container_name: celery-beat
    build: .
    command: celery -A core beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app

  worker:
    container_name: celery-worker
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app

volumes:
  smtp4dev-data: