version: '3.9'


services:
  backend:
    container_name: django
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./env_variables.env
    volumes:
      - ./backend:/app
    command: python3 manage.py runserver 0.0.0.0:8000