version: '3.9'


services:


  psql:
    container_name: blog_psql
    image: postgres:15-alpine3.18
    env_file:
      - ./db.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./secret.sql:/docker-entrypoint-initdb.d/init.sql

    expose:
      - 5432:5432

  backend:
    container_name: django
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./env_variables.env
      - ./db.env
    volumes:
      - ./backend:/app
    depends_on:
      - psql
    command: sh ./bootstrap.sh

  redis:
    container_name: blog-redis
    image: redis
    ports:
      - '6369:6379'
    restart: always
    command: 'redis-server --save --loglevel warning'


  smtp4dev:
    container_name: smtp_blog
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev


  beat:
    container_name: celery-beat
    build: .
    command: celery -A core beat --loglevel=debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    depends_on:
      - backend
      - redis
      - psql
    volumes:
      - ./backend:/app
    env_file:
      - ./db.env


  worker:
    container_name: celery-worker
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - backend
      - redis
      - psql
    volumes:
      - ./backend:/app
    env_file:
      - ./db.env

volumes:
  smtp4dev-data:
