version: '3.9'


services:
  backend:
    container_name: django
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./env_variables.env
    volumes:
      - ./backend:/app
    command: python3 manage.py runserver 0.0.0.0:8000


  redis:
    container_name: blog-redis
    image: redis
    ports:
      - '6369:6379'

    restart: always
    command: 'redis-server --save --loglevel warning'


  smtp4dev:
    container_name: smtp_blog
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev


volumes:
  smtp4dev-data: